### ISSUE TITLE
[Go] kubens error with Azure auth provider: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DerGary** [ahmetb/kubectx#240] opened 2020-06-08 06:13 UTC
When I try to use kubens it just prints an error:

```
C:\>kubens
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1115a97]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc00023bdc0, 0xc000592000, 0xd, 0xc000592000)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:276 +0x397
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc00023bdc0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:206 +0x2b3
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureRoundTripper).RoundTrip(0xc0003533c0, 0xc0001e0600, 0x13e131d, 0xa, 0xc000375d80)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/azure/azure.go:125 +0x88
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0003533e0, 0xc0001e0500, 0xc0003533e0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/transport/round_trippers.go:159 +0x1c7
net/http.send(0xc0001e0500, 0x1584520, 0xc0003533e0, 0x0, 0x0, 0x0, 0xc0000cadd8, 0x2030000, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc00033f3e0, 0xc0001e0500, 0x0, 0x0, 0x0, 0xc0000cadd8, 0x0, 0x1, 0xc000375a20)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc00033f3e0, 0xc0001e0500, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.14.2/x64/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc00026e960, 0xc0000c7830, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:801 +0x3f0
k8s.io/client-go/rest.(*Request).Do(0xc00026e960, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:873 +0xdf
k8s.io/client-go/kubernetes/typed/core/v1.(*namespaces).List(0xc00036ab50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/namespace.go:86 +0x17e
main.queryNamespaces(0xc0000c7e68, 0xc000281408, 0x7, 0xc000281188, 0x7, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:73 +0x2b7
main.ListOp.Run(0x1584900, 0xc0000ca008, 0x1584900, 0xc0000ca010, 0x0, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:37 +0x209
main.main()
        /home/runner/work/kubectx/kubectx/cmd/kubens/main.go:20 +0x10f
```

kubectl and kubectx work.
they all are located in the same folder that is also added to the path.

using newest versions of kubectl kubectx and kubens.
OS: Windows 10 1809

**Comment by ahmetb** [comment] 2020-06-08 06:54
This seems to be a duplicate of #232. Sadly, I have no bandwidth to resolve this, and it seems like the pointer error is coming from Azure’s libraries.

My theory is that this is because we parse kubeconfig from an in-memory byte array (as opposed to parsing from a file); so some systems like azure client-go auth plugin bork out because they cannot find the kubeconfig file path.

**This will be addressed in #229.**

For my record: Does this always happen? Or does it go away when azure successfully fetches a token once (and writes to kubeconfig) when you run something like `kubectl get nodes` and then run `kubens`?

**Comment by DerGary** [comment] 2020-06-08 07:30
@ahmetb 
Thanks for your fast reply.

I just tried running `kubectl get nodes` and directly after that `kubens` and `kubens` returned the same error as described above. So far I did always get this error message when I run `kubens`

**Comment by manoharant** [comment] 2020-06-28 19:32
@ahmetb Do you know when will this issue would be fixed? kubectx and kubens is now my favourite options to manage the k8s cluster and without kubens working, it is difficult for changeing the namespaces often.

**Comment by ahmetb** [comment] 2020-06-28 22:24
@manoharant I currently can’t give an estimate. It seems like we need to debug the client-go repo as that’s where the error is coming from. It seems the azure auth driver isn’t written properly. But we’ll change a few things about how we do read the kubeconfig file, and it might fix that.

**Comment by manoharant** [comment] 2020-07-08 15:28
@ahmetb 
This is working fine when you try to get the credential from azure with --admin option
**az aks get-credentials --resource-group myResourceGroup --name myAKSCluster --admin**

**Comment by ahmetb** [comment] 2020-07-08 15:49
I don’t know what that means. Why does it work?

**Comment by manoharant** [comment] 2020-07-08 18:32
It is the command to get the credential from Azure AKS cluster to local k8s config and after running the above command with --admin option, latest kubens is working fine without the above issue.

**Comment by ahmetb** [comment] 2020-07-08 18:34
I get that. But why? :)

**Comment by AlbertoPeon** [comment] 2020-07-16 15:44
Hi @ahmetb, 
First of all, thanks a lot for `kubectx` and `kubens`, they are great tools!

I have also encountered this issue when using AKS and I can confirmed what @manoharant said, it is working with the `--admin` flag. The only difference of obtaining the kubeconfig with `az aks get-credentials` using `--admin` is that you [get admin credentials](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-get-credentials) that will skip the RBAC check when running a `kubectl` for the first time.

In practice, this results in a different context YAML format.

Without `--admin` (and once passed the RBAC check):  

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: '...'
    server: '...'
  name: mycluster
contexts:
- context:
    cluster: mycluster
    user: myUser
  name: mycontext
current-context: mycontext
kind: Config
preferences: {}
users:
- name: myUser
  user:
    auth-provider:
      config:
        access-token: '...'
        apiserver-id: '...'
        client-id: '...'
        environment: '...'
        expires-in: "..."
        expires-on: "..."
        refresh-token: '...'
        tenant-id: '...'
      name: '...'
```

With `--admin`:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: '...'
    server: '...'
  name: mycluster
contexts:
- context:
    cluster: mycluster
    user: myAdminUser
  name: mycontext
current-context: mycontext
kind: Config
preferences: {}
users:
- name: myAdminUser
  user:
    client-certificate-data: '...'
    client-key-data: '...'
    token: '...'
```

Perhaps the parsing of the library does not support the Azure specific fields? Thanks!

**Comment by mhoyer** [comment] 2020-10-22 11:43
Not sure if this is a complete different issue, but at least the stack trace looks quite similar for me when trying to use the Go version [0.9.1](https://github.com/ahmetb/kubectx/releases/tag/v0.9.1) of `kubens` on my git bash under Windows 10. Obvious difference, for me the `oidcAuthProvider` has the nil pointer issue (not the `azureTokenSource`): 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x11347a1]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*oidcAuthProvider).idToken(0xc00045c6c0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/oidc/oidc.go:281 +0x701
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*roundTripper).RoundTrip(0xc00046c640, 0xc000226600, 0x13e1398, 0xa, 0xc0004808e0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/plugin/pkg/client/auth/oidc/oidc.go:199 +0x83
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc00046c660, 0xc000226500, 0xc00046c660, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/transport/round_trippers.go:159 +0x1c7
net/http.send(0xc000226500, 0x1584660, 0xc00046c660, 0x0, 0x0, 0x0, 0xc000006d68, 0x2030000, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:252 +0x445
net/http.(*Client).send(0xc00045d080, 0xc000226500, 0x0, 0x0, 0x0, 0xc000006d68, 0x0, 0x1, 0xc000480580)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:176 +0x101
net/http.(*Client).do(0xc00045d080, 0xc000226500, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:699 +0x451
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.14.4/x64/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc0002b6d20, 0xc000509830, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:801 +0x3f0
k8s.io/client-go/rest.(*Request).Do(0xc0002b6d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/rest/request.go:873 +0xdf
k8s.io/client-go/kubernetes/typed/core/v1.(*namespaces).List(0xc000467880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/namespace.go:86 +0x17e
main.queryNamespaces(0xc000121e68, 0xc0002ff2c0, 0x11, 0xc0002f2a58, 0x6, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:64 +0x24a
main.ListOp.Run(0x1583fe0, 0xc00006c140, 0x1583fe0, 0xc00006c190, 0x0, 0x0)
        /home/runner/work/kubectx/kubectx/cmd/kubens/list.go:36 +0x209
main.main()
        /home/runner/work/kubectx/kubectx/cmd/kubens/main.go:21 +0x116
```

**Comment by sabbox** [comment] 2020-10-22 12:00
@mhoyer that looks like very well the issue related with the outdated azure auth plugin within k8s.io/client-go
try my fork and see if it's working: https://github.com/sabbox/kubectx/releases/tag/v0.9.7
I think I've addressed both issues already in my fork (I'm using Azure AKS + OpenID)
My PR #260 that is addressing first issue is hanging around for quite a while

**Comment by ahmetb** [comment] 2020-10-23 00:10
Sorry for the stall here folks. The problem right now is that we are striving to parse the file **once** (in order to preserve its fields and structure when we modify it).

I'm trying to understand what part is exactly causing the Azure issue. Sure, we can hack it by merging #260, but that throws the niceties and optimizations out of the window (might as well just shell out to "kubectl" at that point and have a noticeably slower experience).

Maybe there's something we can do, like if the auth provider is azure, we try to make a call first, causing kubeconfig file to be updated, then we can finally parse it into the memory and manage its lifecycle.

**Comment by sabbox** [comment] 2020-12-07 11:53
@ahmetb I guess you are right, #260 is hack 
if go-client API is allowing to create client in read-only mode no auth plugin should fail eventually.
I've created a PR to address this issue in go-client https://github.com/kubernetes/kubernetes/pull/97095 
let's see how it goes

**Comment by ahmetb** [comment] 2020-12-29 21:29
@sabbox thanks for following up with that PR. If it gets merged, please notify here (or just make a patch bumping the deps). Did you compile Krew with your patch and observe if it fixes the issue?

**Comment by sabbox** [comment] 2020-12-30 05:42
> @sabbox thanks for following up with that PR. If it gets merged, please notify here (or just make a patch bumping the deps). 

@ahmetb will do a patch for kubens when/if go-client PR gets merged.

> Did you compile Krew with your patch and observe if it fixes the issue?

No, I didn't, not sure how to do it though

**Comment by sabbox** [comment] 2021-01-16 20:03
@ahmetb PR kubernetes/kubernetes#97095 eventually got into master

currently k8s master is at 1.21 and go-client 0.21 
Not sure whether it is a good idea to upgrade go-client in kubectx by skipping a few minor versions 

I will try to backport the PR to 1.18+ and/or to 1.19+
Then I will bump go-client up in kubectx to the proper version

**Comment by sabbox** [comment] 2021-01-16 20:10
@ahmetb, I also close PR #260 cause it's irrelevant

**Comment by ahmetb** [comment] 2021-01-17 03:27
@sabbox I don't mind vendoring a newer client-go. It shouldn't have any negative consequences. We don't need to wait for a kubectl release.

**Comment by sabbox** [comment] 2021-01-18 21:32
@ahmetb no, we don't 

what I'm saying is that PR is accessible only in `go-client v0.21.0-alpha.1` and in the master branch.
So we have a few options:
- start using `go-client v0.21.0-alpha.1` right away (eventually migrate to stable `go-client v0.21.0` when available)
- backport PR to `v0.20.x` and use it when go-client is released 

what do you think?

**Comment by ahmetb** [comment] 2021-01-19 18:19
> * start using `go-client v0.21.0-alpha.1` right away (eventually migrate to stable `go-client v0.21.0` when available)

this is fine. tbh we rely on very minimal and basic functionality from client-go (kubeconfig file parsing, and querying namespaces etc) so I think it's acceptable risk.

**Comment by sabbox** [comment] 2021-01-19 22:56
all right then

**Closed** 2021-02-02 23:38 UTC
Labels: Bug, Go implementation

**Comment by AndrewSav** [comment] 2021-02-11 08:27
Just want to point out again to @ahmetb that it's not _just_ the azure. I'm not using azure and I'm getting a similar stack trace that @mhoyer is getting that does not mention azure.

**Comment by AndrewSav** [comment] 2021-02-11 08:35
Never mind the fix worked for oidc too.
