### ISSUE TITLE
Kubens does not work with Rancher

### ISSUE THREAD

**Issue by aaronkjones** [ahmetb/kubectx#155] opened 2019-06-05 17:04 UTC
## Problem

 **I am new to using Rancher w/ k8s, so this may not be a problem at all.**

Rancher includes RBAC on top of k8s for project isolation. Because of this, kubens cannot list namespaces.

## Error
```
kubens mynamespace
Error from server (Forbidden): namespaces is forbidden: User "u-8mx6g7g8" cannot list resource "namespaces" in API group "" at the cluster scope
error: no namespace exists with name "mynamespace".
```

## Proposal

Allow setting namespace without listing namespaces.

**Comment by ahmetb** [comment] 2019-06-05 17:16
Seems to be a duplicate of #83, which we have no solution for right now.

Supporting this would add visible overhead to all other users, so we're holding it off at the moment. If we were to rewrite kubectx and kubens in Go (#115) at some point, we can solve this.

**Closed by ahmetb** 2019-06-05 17:16 UTC
