### ISSUE TITLE
Typos in help output of kubens version 0.9

### ISSUE THREAD

**Issue by eshepelyuk** [ahmetb/kubectx#234] opened 2020-05-28 17:35 UTC
The output should be self explanatory :)

```
/d/projects
$ kubens --help
USAGE:
  kubectx                    : list the namespaces in the current context
  kubectx <NAME>             : change the active namespace of current context
  kubectx -                  : switch to the previous namespace in this context
  kubectx -c, --current      : show the current namespace
  kubectx -h,--help          : show this message
```

**Comment by ahmetb** [comment] 2020-05-28 17:41
duplicate of #224

**Closed by ahmetb** 2020-05-28 17:41 UTC
